databases:
  - name: real-estate-db
    databaseName: real_estate_db
    user: real_estate_user
    plan: free

services:
  # Backend API
  - type: web
    name: real-estate-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: real-estate-db
          property: connectionString
    healthCheckPath: /api/health

 